# Generated by Django 3.0.8 on 2020-12-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage1', '0002_auto_20201213_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stages',
            old_name='userwatch',
            new_name='userstat',
        ),
    ]
